export const SET_QUIZ = "quiz/SET_QUIZ"
export const SET_USER = "quiz/SET_USER"
export const UPDATE_SCORECARD = "quiz/UPDATE_SCORECARD"
export const UPDATE_QUESTION_INDEX = "quiz/UPDATE_QUESTION_INDEX"
export const TOGGLE_COMPLETE = "quiz/TOGGLE_COMPLETE"
export const RESET_QUIZ = "quiz/RESET_QUIZ"
